"""Documentary answers per test ID. Used when the live test could not run (status then reflects documents only),
and as the primary answer for Part C. Paths are relative to verification/.

Status rules: doc_status is "DOCUMENTED (not observed)" when a cited document answers the question, "BLOCKED"
when no document answers it and the live test is the only way, and "NOT DETERMINABLE EMPIRICALLY" for Part C.
"""

D = "evidence/docs/"
SDK = "evidence/sdk/sdk_facts.md"

QUESTIONS = {
    "A1": "Does calling one Subscriber ring all of its registered devices?",
    "A2": "First-answer-wins: when one device answers, do the others stop ringing, and how fast?",
    "A3": "Does reject() on one device stop all devices on that Subscriber, and other Subscribers in the same parallel group?",
    "A4": "What does the inbound SWML webhook request contain?",
    "A5": "Can the browser dial an SWML webhook address with userVariables, and what caller identity does the webhook receive?",
    "A6": "connect serial fallback to a phone number after the Subscriber times out, and connect_result branching",
    "A7": "Exact REST command names and payloads for record start, pause, resume, stop, and hangup",
    "A8": "Stereo MP3 of both parties: format and channel mapping, inbound and outbound",
    "A9": "Which status webhooks fire for connect, recording and call end, and where is the REST recording callback configured?",
    "A10": "Which call_id must REST commands target (anchor rule)?",
    "A11": "Maximum devices per Subscriber",
    "A12": "Cost per call by product",
    "B1": "No device registered for a Subscriber in the parallel list: fail fast or wait for timeout?",
    "B2": "Parallel destination cap for connect.parallel",
    "B3": "Does an expiring SAT drop an active call?",
    "B4": "Does automatic refresh work (backend refresh vs fingerprint + sat:refresh)?",
    "B5": "Does deleting a Subscriber revoke active sessions and in-progress calls?",
    "B6": "Can custom data reach the browser on inbound calls?",
    "B7": "What caller ID does the browser see on inbound, and can connect.from override it?",
    "B8": "What does the remote party hear during browser hold, and is it recorded?",
    "B9": "Can a device on an active call receive a second inbound call?",
    "B10": "Server-side transfer of a connected call to another Subscriber and to a phone number",
    "B11": "Webhook authenticity: signature header and validation",
    "B12": "Webhook reliability: retries and timeouts when the backend is slow or returns 500",
    "B13": "Recording retention and deletion via API",
    "B14": "Outbound CPS: what happens when the default limit is exceeded?",
    "B15": "Negotiated codecs on the WebRTC leg and the PSTN leg",
    "B16": "Can one Subscriber hold multiple simultaneous connected calls across devices?",
    "B17": "Can one browser register as two Subscribers?",
    "B18": "Does connect_result differ between decline, no answer, and no registrations?",
    "C1": "Is the $3/month Subscriber fee billed per Subscriber created or per Subscriber registered in the period?",
    "C2": "How is the outbound CPS limit raised, and to what?",
    "C3": "911 from browser softphones",
    "C4": "Can numbers ported from Telnyx carry both existing 10DLC campaigns and voice?",
}

DOC = {
    "A1": dict(status="DOCUMENTED (not observed)",
               answer="Documented yes. The Server SDK dial reference states that dialing a Subscriber's resource address \"rings every live registration of a subscriber at once\". The Browser SDK side only rings while a device is registered (`register()` marks the Subscriber online). Not yet observed with 3 devices.",
               cites=[D + "extra/multi_device_and_reject.md", SDK + " (Item 1, register)"]),
    "A2": dict(status="BLOCKED",
               answer="Not answered by documentation. The SDK exposes per-call `status$` with values new, trying, ringing, connecting, connected, recovering, disconnecting, disconnected, failed, destroyed, so the harness can time the transition off `ringing` on the other devices, but neither the docs nor the SDK state what the losing devices see or how fast. Needs the live run.",
               cites=[SDK + " (Item 2, CallStatus)"]),
    "A3": dict(status="BLOCKED",
               answer="Not answered by documentation. The reject() reference says \"the caller-side rings stop, no media is negotiated, and the call instance transitions to disconnected\" for the rejecting device, but nothing documents the effect on other devices of the same Subscriber or on other parallel destinations. The backend workaround (calling.end on the anchor leg via REST) uses documented commands; its stop latency needs the live run.",
               cites=[D + "extra/multi_device_and_reject.md", D + "rest_facts.json (1_calling_rest_api)"]),
    "A4": dict(status="DOCUMENTED (not observed)",
               answer="Documented: an HTTP POST with a JSON body whose top-level keys are `call`, `vars`, `envs`, `params` (`params` is `{}` on the first inbound fetch). `call` carries `call_id`, `call_state`, `direction`, `from`, `to`, `headers[]`, `node_id`, `project_id`, `segment_id`, `space_id`, `type` (sip, phone, webrtc) and `sip_data` for SIP. Requests are signed with `X-SignalWire-Signature`. Reply with `application/json` or YAML. Exact live payload not yet captured.",
               cites=[D + "swml/public_swml_calling_webhook_payload.md", D + "swml_facts.json (5)"]),
    "A5": dict(status="DOCUMENTED (not observed)",
               answer="Partly documented. The v4 dial shape is confirmed from the published SDK types: `client.dial('/private/<name>', { audio: true, video: false, userVariables: { to, crm_call_id } })`; there is no `to` option, the destination is the first argument. Which webhook field carries userVariables, and which field identifies the calling Subscriber, are not documented for the SWML fetch: `vars.userVariables` appears only in SWAIG examples, and `call.from` is described only as \"the number/URI that initiated this call\". The Browser SDK guide shows a Subscriber `from` as an address like `/private/alice`. The forged-identity check needs the live run.",
               cites=[SDK + " (Item 3)", D + "swml_facts.json (5)", D + "extra/multi_device_and_reject.md"]),
    "A6": dict(status="DOCUMENTED (not observed)",
               answer="Documented: `connect` accepts `serial` (try in order), `parallel` or `serial_parallel`, with a per-destination `timeout`, so a Subscriber address followed by a phone number gives fallback. After `connect`, `connect_result` is `connected` or `failed` (and `return_value` equals it); `connect.result` or a `switch` on `connect_result` selects the voicemail branch. `connect_failed_reason` has no documented value list. Not yet observed.",
               cites=[D + "swml/public_swml_connect.md", D + "swml_facts.json (1, 2)"]),
    "A7": dict(status="DOCUMENTED (not observed)",
               answer="Documented on `POST /api/calling/calls` with Basic auth: `{\"command\":\"calling.record\",\"id\":<call_id>,\"params\":{\"control_id\":..,\"audio\":{\"format\":\"mp3\",\"stereo\":true,\"direction\":\"both\"}}}`; `calling.record.pause` with `{control_id, behavior}` where behavior is `skip` (default) or `silence`; `calling.record.resume` and `calling.record.stop` with `{control_id}`; hangup is `calling.end` with `{reason:\"hangup\"}`. The exact nesting of `audio` under `params` comes from SDK-level docs and needs the live run to confirm.",
               cites=[D + "rest/calling_api_call_commands.md", D + "rest_facts.json (1_calling_rest_api)"]),
    "A8": dict(status="BLOCKED",
               answer="Not answered by documentation. `stereo: true` with `format: mp3` is a documented option, but which party lands on which channel is not documented. The FFT analyzer that answers this is built and passes its self-test on synthetic audio; it needs real recordings.",
               cites=[D + "swml_facts.json (3, gaps)", "evidence/selftest/audio/result.json"]),
    "A9": dict(status="DOCUMENTED (not observed)",
               answer="Documented events: `connect.status_url` posts `calling.call.connect` (connect_state connecting, connected, failed, disconnected); `call_state_url` posts `calling.call.state` (created, ringing, answered, ended with end_reason); recording `status_url` posts `calling.call.record` (state recording, paused, finished, no_input, error, with url, recording_id, duration, size). For a REST-started recording the callback goes in `params.status_url` of `calling.record` per SDK-level docs. Which location delivers in practice needs the live run.",
               cites=[D + "swml_facts.json (1, 3)", D + "rest/swml_record_call_status_callbacks.md"]),
    "A10": dict(status="BLOCKED",
                answer="Not documented. No source searched states an anchor-leg rule for REST commands. The harness sends `calling.record` to both legs on inbound and outbound calls to settle it.",
                cites=[D + "rest_facts.json (1_calling_rest_api, gaps)"]),
    "A11": dict(status="BLOCKED",
                answer="Not documented. No maximum devices per Subscriber appears in docs, and the SDK has no client-side device limit constant. Needs the 5, 10, 20 device run.",
                cites=[SDK + " (Item 7)", D + "extra/multi_device_and_reject.md"]),
    "A12": dict(status="BLOCKED",
                answer="No calls were placed, so there is no per-call cost data. Published list rates (not observed charges): WebRTC $0.003/min each way, local PSTN $0.0066/min inbound and $0.008/min outbound, call recording $0.002/min. Per-call charges come from `GET /api/voice/logs`; its cost fields are not documented and must be read from a live response.",
                cites=[D + "rest/pricing.md", D + "rest/voice_logs_api.md"]),
    "B1": dict(status="BLOCKED",
               answer="Not documented. Whether `connect` fails fast or waits for `timeout` when a Subscriber has no registrations is not stated. Needs the live run.",
               cites=[D + "swml_facts.json (1)"]),
    "B2": dict(status="BLOCKED",
               answer="Not documented. No parallel destination limit appears in SWML docs or the SWML JSON schema (no maxItems). The reported 20-destination limit is not in any source searched; the only related figure is cXML `<Dial>` allowing up to 10 `<Sip>` nouns, which is a different product.",
               cites=[D + "swml_facts.json (1, gaps)"]),
    "B3": dict(status="BLOCKED",
               answer="Not documented for active calls. The SDK validates `expiry_at` only at construction (`Provided credentials have expired`) and on reconnect; nothing in the docs or SDK says an established media session is torn down at token expiry. Needs the live run.",
               cites=[SDK + " (Item 1)"]),
    "B4": dict(status="DOCUMENTED (not observed)",
               answer="Documented in the SDK: pass a provider with `refresh()` and `expiry_at` (ms); the SDK calls `refresh()` 5 s before expiry and retries up to 5 times with backoff, then emits `TokenRefreshError` on `client.errors$` and disconnects. With a token minted with `scope: [\"sat:refresh\"]` and the SDK's `fingerprint`, the SDK refreshes on its own through `/api/fabric/subscriber/devices/token` and `/devices/refresh`. Backend refresh uses `POST /api/fabric/subscribers/tokens/refresh {refresh_token}`. Not yet observed.",
               cites=[SDK + " (Item 1)", D + "rest/fabric_subscribers_and_tokens.md"]),
    "B5": dict(status="BLOCKED",
               answer="Not documented. `DELETE /api/fabric/resources/subscribers/{id}` returns 204; the effect on live registrations and in-progress calls is not stated in public docs. Needs the live run.",
               cites=[D + "rest_facts.json (2_fabric_subscribers)"]),
    "B6": dict(status="DOCUMENTED (not observed)",
               answer="Documented as not available through headers: the v4 inbound `Call` object has no headers or custom-data property, and SWML `connect.headers` is documented as having no effect on calls to phone numbers, with no statement about WebRTC destinations. The SDK maps `userVariables` from the inbound invite onto `call.userVariables`, so that is the only documented path for custom data. Whether SWML can populate it for a Subscriber destination needs the live run.",
               cites=[SDK + " (Item 2)", D + "swml_facts.json (1)"]),
    "B7": dict(status="BLOCKED",
               answer="Not documented for PSTN callers. The SDK maps `from` from the invite's `caller_id_number` and `fromName` from `caller_id_name`. The Browser SDK guide shows `from` as an address for Subscriber-to-Subscriber calls. Whether a PSTN caller appears as the original number or the Space number, and whether `connect.from` overrides it for a Resource Address, are not documented.",
               cites=[SDK + " (Item 2)", D + "extra/multi_device_and_reject.md", D + "swml_facts.json (8)"]),
    "B8": dict(status="BLOCKED",
               answer="Not documented for the Browser SDK. `call.toggleHold()` is the only hold control in v4. RELAY server-side hold docs say the remote party \"hears hold music or silence\", without saying which. Needs the recording FFT.",
               cites=[SDK + " (Item 4)", D + "swml/public_callerid_and_hold.md"]),
    "B9": dict(status="DOCUMENTED (not observed)",
               answer="Documented at the SDK level: `incomingCalls$` emits the full list of inbound calls and \"two simultaneous callers land in the same emission\"; the SDK does not queue or pick. Whether the platform offers a second call to a device already on a call needs the live run.",
               cites=[D + "extra/multi_device_and_reject.md", SDK + " (Item 2)"]),
    "B10": dict(status="DOCUMENTED (not observed)",
                answer="Documented: `calling.transfer` with `dest` (an SWML URL or inline document) on the call; SWML `transfer` also takes `dest`. Pointing `dest` at SWML that `connect`s to another Subscriber address or a phone number is the documented pattern. The browser-side `call.transfer({destination})` also exists in v4. What each party experiences needs the live run.",
                cites=[D + "rest_facts.json (1_calling_rest_api)", SDK + " (Item 4)"]),
    "B11": dict(status="DOCUMENTED (not observed)",
                answer="Documented: `X-SignalWire-Signature` is hex HMAC-SHA1 and `X-SignalWire-Sha256-Signature` is hex HMAC-SHA256, both over `url + raw_body`, keyed with the project Signing Key (not the API token). The harness validator agrees with SignalWire's published Python RequestValidator and rejects a tampered body (local self-test). Not yet checked against a live webhook.",
                cites=[D + "swml/public_swml_webhook_security.md", D + "swml/sdk_webhook_signature_validation.md", "evidence/selftest/signature/result.json"]),
    "B12": dict(status="DOCUMENTED (not observed)",
                answer="Partly documented: SignalWire waits about 5 seconds for SWML, then uses `fallback_request_url` on timeout, 5xx or invalid SWML, and the call fails with `http_retrieval_error` if nothing usable returns. Retry counts for SWML fetches and SWML status callbacks are not documented (the 3-attempt status callback retry applies to cXML).",
                cites=[D + "swml/public_swml_webhook_reliability.md", D + "swml/public_compat_webhooks_timeouts_retries.md"]),
    "B13": dict(status="DOCUMENTED (not observed)",
                answer="Documented: `GET /api/relay/rest/recordings`, `GET` and `DELETE /api/relay/rest/recordings/{id}` (also the cXML Recordings endpoints). Retention: the cXML docs say recordings remain stored indefinitely until deleted. Whether the media URL stops serving after delete needs the live run.",
                cites=[D + "rest/recordings_api.md"]),
    "B14": dict(status="DOCUMENTED (not observed)",
                answer="Documented: the default is 1 call per second, and calls above it are queued (backlog of 10,000) rather than rejected; when the backlog is full SignalWire stops adding calls. The error returned at that point is not documented.",
                cites=[D + "rest/platform_rate_limits.md"]),
    "B15": dict(status="BLOCKED",
                answer="Not documented. The SDK offers `preferredAudioCodecs` on dial and exposes `call.rtcPeerConnection` for `getStats()`; it has no codec getter. SWML `connect.codecs` sets offered codecs. Negotiated codecs need the live run.",
                cites=[SDK + " (Items 3, 6)", D + "swml_facts.json (1)"]),
    "B16": dict(status="BLOCKED",
                answer="Not documented. No source states whether one Subscriber can hold two connected calls on two devices at once. Needs the live run.",
                cites=[D + "extra/multi_device_and_reject.md"]),
    "B17": dict(status="DOCUMENTED (not observed)",
                answer="Partly documented from the SDK source: multiple `SignalWire` instances can be created in one page, but `sw:cached_credential`, `sw:client_bound`, `sw:preferences` and the IndexedDB DPoP key are shared across instances. Pass a separate `storageImplementation` to each client to keep two Subscribers apart. Whether the platform accepts both registrations needs the live run.",
                cites=[SDK + " (Item 5)"]),
    "B18": dict(status="DOCUMENTED (not observed)",
                answer="Documented: `connect_result` has two values, `connected` and `failed`, so decline, no answer and no registrations all read `failed`. Any distinction would be in `connect_failed_reason` (no documented values) or in `call_state_url` `end_reason` (hangup, busy, no_answer, cancel, declined, error).",
                cites=[D + "swml_facts.json (1)"]),
    "C1": dict(status="NOT DETERMINABLE EMPIRICALLY",
               answer="Public pricing lists Subscriber at $3.00/month and the Subscribers page says \"$3/user/month\". No public source says whether this is charged per Subscriber created, per Subscriber existing, or per Subscriber that registered in the period, and no usage API documented exposes Subscriber line items. Confirm with Sales.",
               cites=[D + "rest/pricing.md"], confirm="Sales"),
    "C2": dict(status="NOT DETERMINABLE EMPIRICALLY",
               answer="Docs: the default is 1 CPS with a 10,000-call backlog. Throughput is raised by contacting Support; the backlog by the Space Increase Request Form. The pricing page lists paid CPS tiers at $15 to $40 per month each with a 3-month commitment. The ceiling for this account must come from Sales or Support.",
               cites=[D + "rest/platform_rate_limits.md", D + "rest/pricing.md"], confirm="Sales / Support"),
    "C3": dict(status="NOT DETERMINABLE EMPIRICALLY",
               answer="Not tested by design. SignalWire E911 is configured per phone number with a registered US address (`POST /api/relay/rest/addresses`, then assigned to the number; status pending then active) at $0.75/month. There is no dynamic location: PIDF-LO is not used and the docs say to update the address when a device moves. Nothing in the docs covers 911 placed from WebRTC Subscribers. For counsel: Kari's Law requires direct 911 dialing without a prefix and on-site notification for multi-line telephone systems, and RAY BAUM's Act Section 506 requires a dispatchable location, including for non-fixed devices. Neither law is addressed in the SignalWire docs searched.",
               cites=[D + "rest/e911.md"], confirm="Counsel and SignalWire Support (E911)"),
    "C4": dict(status="NOT DETERMINABLE EMPIRICALLY",
               answer="Docs: voice and messaging both work on ported numbers, but 10DLC campaigns do not transfer automatically. Each messaging provider is its own CSP registration, so a customer migrating from another provider re-registers Brand and Campaign with SignalWire, or, if they are their own CSP, selects SignalWire as the upstream CNP. The old registration stays in place until deactivated. Port-in is free and takes about a week. Confirm with Carrier Ops whether an existing campaign can be moved by CNP change without re-vetting.",
               cites=[D + "rest/porting_and_10dlc.md"], confirm="Carrier Ops"),
}

SHORT = {
    "A1": "Documented yes: dialing a Subscriber rings every live registration at once; not yet observed.",
    "A2": "Unknown: no document states what the other devices see or how fast; live test required.",
    "A3": "Unknown: reject() stops the rejecting device, but its effect on other devices or parallel Subscribers is undocumented.",
    "A4": "POST JSON with call, vars, envs, params; call has call_id, from, to, type, direction, headers and more.",
    "A5": "dial(address, { userVariables }) is the confirmed v4 shape; the webhook field for userVariables and caller identity is undocumented.",
    "A6": "connect.serial gives fallback; connect_result is connected or failed and drives the voicemail branch.",
    "A7": "calling.record, calling.record.pause (behavior skip or silence), calling.record.resume, calling.record.stop, calling.end.",
    "A8": "Unknown: stereo MP3 is supported, but channel-to-party mapping is undocumented; analyzer ready.",
    "A9": "calling.call.connect, calling.call.state and calling.call.record events; REST recording callback goes in params.status_url.",
    "A10": "Unknown: no anchor-leg rule is documented; live test sends commands to both legs.",
    "A11": "Unknown: no device limit is documented in the docs or the SDK.",
    "A12": "No per-call cost data (no calls placed); list rates WebRTC $0.003/min, local PSTN $0.0066 in / $0.008 out, recording $0.002/min.",
    "B1": "Unknown: fail-fast versus timeout with zero registrations is undocumented.",
    "B2": "Unknown: no parallel cap is documented; the 20-destination figure appears in no source.",
    "B3": "Unknown: nothing says an established call drops at SAT expiry.",
    "B4": "Documented: refresh() is called 5 s before expiry with 5 retries, then TokenRefreshError; sat:refresh enables SDK self-refresh.",
    "B5": "Unknown: delete returns 204; effect on live sessions and calls is undocumented.",
    "B6": "Only userVariables is a documented path; the v4 Call object has no headers property.",
    "B7": "Unknown for PSTN callers: from maps to the invite caller_id_number; override behavior undocumented.",
    "B8": "Unknown: v4 offers toggleHold(); what the remote party hears is undocumented.",
    "B9": "SDK lists every inbound call, including a second one; platform offer behavior unverified.",
    "B10": "calling.transfer with dest pointing at SWML that connects to the target is the documented method.",
    "B11": "X-SignalWire-Signature = hex HMAC-SHA1(Signing Key, url + raw_body); validator proven against SignalWire's library.",
    "B12": "About 5 s wait, then fallback_request_url on timeout or 5xx; SWML retry counts are undocumented.",
    "B13": "List, get and delete via /api/relay/rest/recordings; retention is indefinite until deleted.",
    "B14": "Default 1 CPS; excess calls are queued (10,000 backlog), not rejected.",
    "B15": "Unknown: read via call.rtcPeerConnection.getStats(); no codec getter in the SDK.",
    "B16": "Unknown: concurrent calls per Subscriber are undocumented.",
    "B17": "Possible in the SDK with a separate storageImplementation per client; platform acceptance unverified.",
    "B18": "Documented: connect_result is connected or failed only, so all three cases read failed.",
    "C1": "Not public: $3.00/month per Subscriber is listed, but the billing basis is not stated. Confirm with Sales.",
    "C2": "Default 1 CPS; raise via Support, paid tiers $15 to $40/month listed. Confirm ceiling with Sales/Support.",
    "C3": "Not tested. E911 is per number with a static US address; WebRTC 911 is undocumented. Review with counsel.",
    "C4": "Voice ports freely; 10DLC campaigns need re-registration or a CNP change. Confirm with Carrier Ops.",
}
